### ISSUE TITLE
Prepare initial contribution

### ISSUE THREAD

**Issue by sbckr** [carbynestack/nettle#2]
Things to be done **prior** to changing the repo visibility to `public`:

- [x] Provide 3rd-party-licenses
  - generate folder
  - collect license files (from pip venv requirements.txt and python licenses)
- [x] Add Code of Conduct badge and file
- [x] Add github workflow for test execution
- [x] Rename MpcStrategy.amphora_model_id
- [x] Make CS Backend configurable
- [x] Trigger OSS clearing

Things to be done **after** changing the repo visibility to `public`:

- [x] Move CSEP#0055 to carbynestack/carbynestack (can be done only after IP has been filed)
- [x] Add Codacy, Codecov, and Snyk support

**Comment by strieflin** [comment]
All tasks completed (see carbynestack/carbynestack#71 for the CSEP migration). Closing this.
